<?php

namespace AppBundle\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * FacturesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FacturesRepository extends EntityRepository
{



}
